language: c
compiler:
 - clang
 - gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install --reinstall -qq build-essential
script:
 - ./autogen.sh
 - ./configure
 - make
 - make DESTDIR='bin' install
 - $CC -Wall -g -DDEBUG --std=c99 -D_POSIX_C_SOURCE=200809L test-nap.c -lm -o test-nap
 - ./test-nap
