language: c
compiler:
 - clang
 - gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install --reinstall -qq build-essential
script:
 - ./autogen.sh
 - ./configure
 - make
 - make DESTDIR='bin' install
 - $CC -o test-nap test-nap.c
 - ./test-nap
